apiVersion: v1
kind: Service
metadata:
  name: portfolio-client
  labels:
    app: portfolio-client
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: portfolio-client
---
apiVersion: v1
kind: Service
metadata:
  name: portfolio-server
  labels:
    app: portfolio-server
spec:
  type: ClusterIP
  ports:
    - port: 3001
      targetPort: 3001
      protocol: TCP
  selector:
    app: portfolio-server
